In [1]:
import pandas as pd
import numpy as np

In [2]:
df_0 = pd.read_csv('airdrop_list.csv')

In [3]:
df_0

,rewards_to_collect_till_now,projected_rewards_to_collect,rewards_till_now,projected_rewards,account,last_sync_time,last_sync_time_epoch,now_utc,now_epoch,last_redeem_time,...,basic_start,seed_start,program_end,actual_stake,virtual_stake,actual_base,virtual_base,last_sync_reward,total_boost,collected_rewards
0,245497.264558,670481.764811,245497.264558,670481.764811,\xfdb3519f49149ffbd787927cd09792eeaccdd56c,2021-08-27T08:37:25+00:00,1630053445,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,7.714927e+06,5787,7032,0.0,0,0.0
1,153435.790349,419051.103007,153435.790349,419051.103007,\x833fe60d09882f0013fd86fafa2aeb3854e51637,2021-08-27T08:37:25+00:00,1630053445,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,4.821829e+06,5787,7032,0.0,0,0.0
2,110653.295318,302207.101414,110653.295318,302207.101414,\x1ac5d648599b9767b1a1bd13eb8bf082b4c157c2,2021-08-27T08:37:25+00:00,1630053445,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,3.477359e+06,5787,7032,0.0,0,0.0
3,82855.326788,226287.595624,82855.326788,226287.595624,\xb60b99d3c52d1b748e93953fac6dd7a69e934af5,2021-08-27T08:37:25+00:00,1630053445,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,2.603788e+06,5787,7032,0.0,0,0.0
4,46977.015504,128299.727971,46977.015504,128299.727971,\x82612e25bcb90109dd964d16416b7d500aa462c6,2021-08-27T08:37:25+00:00,1630053445,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,1.476286e+06,5787,7032,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,0.000000,0.000000,0.000000,0.000000,\x8d313be9a5f5abb56e696d2bb2e5ea2673e326c6,2021-09-20T20:13:05+00:00,1632168785,2021-10-18T20:59:41+00:00,1.634591e+09,2021-09-20T20:13:05+00:00,...,1627387200,1630065600,1642424400,0.0,0.000000e+00,5787,7032,0.0,1585,0.0
1147,0.000000,0.000000,0.000000,0.000000,\xb29dbc6c47d74eb78365ae3a54b1fa12cacb5cef,2021-09-21T04:43:10+00:00,1632199390,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,0.000000e+00,5787,7032,0.0,0,0.0
1148,0.000000,0.000000,0.000000,0.000000,\x37b5c1a4ed75215eaa6848f6415abe8677a3f302,2021-10-16T15:59:20+00:00,1634399960,2021-10-18T20:59:41+00:00,1.634591e+09,2021-09-20T20:26:55+00:00,...,1627387200,1630065600,1642424400,0.0,0.000000e+00,5787,7032,0.0,634,0.0
1149,0.000000,0.000000,0.000000,0.000000,\xe6c5bbe021b31ad681cb2dceb8ad1889868c0f0e,2021-09-17T17:33:20+00:00,1631900000,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,0.000000e+00,5787,7032,0.0,0,0.0
1150,0.000000,0.000000,0.000000,0.000000,\x16ad333d14dd99c0ff92f523d56ef4b76033c984,2021-09-20T19:42:15+00:00,1632166935,2021-10-18T20:59:41+00:00,1.634591e+09,NaN,...,1627387200,1630065600,1642424400,0.0,0.000000e+00,5787,7032,0.0,0,0.0

In [12]:
df_0.columns

Index(['rewards_to_collect_till_now', 'projected_rewards_to_collect',
       'rewards_till_now', 'projected_rewards', 'account', 'last_sync_time',
       'last_sync_time_epoch', 'now_utc', 'now_epoch', 'last_redeem_time',
       'last_redeem_time_epoch', 'last_collect_time',
       'last_collect_time_epoch', 'basic_start', 'seed_start', 'program_end',
       'actual_stake', 'virtual_stake', 'actual_base', 'virtual_base',
       'last_sync_reward', 'total_boost', 'collected_rewards'],
      dtype='object')

In [4]:
df_0['actual_stake'].sum()

13206978.28953696

In [5]:
df_1 = df_0[["account", "actual_stake"]]

In [6]:
df_1.to_csv('df_1.csv')

In [7]:
in_csv = 'df_1.csv'

In [8]:
number_lines = sum(1 for row in (open(in_csv)))

In [10]:
rowsize = 100
for i in range(1,number_lines,rowsize):
    df = pd.read_csv(in_csv,
          header=None,
          nrows = rowsize,
          skiprows = i)
    
    df = df.iloc[: , 1:]
    
    df[1] = '0' + df[1].str[1:]

    out_csv = 'input' + str(i) + '.csv'
    
    df.to_csv(out_csv,
          index=False,
          header=True,
          mode='a',
          chunksize=rowsize)